name: 'S3 Deploy'
description: 'Deploy a static website to AWS S3 and invalidate CloudFront distribution'
inputs:
  folder:
    description: 'Directory to deploy'
    required: true
  bucket:
    description: 'Name of AWS Bucket'
    required: true
  dist-id:
    description: 'AWS CloudFront distribution ID'
    required: true
  invalidations:
    description: 'AWS CloudFront invalidations path(s)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
